# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RISC-V.xdc

# IP: ip/FIFO_data/FIFO_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_data || ORIG_REF_NAME==FIFO_data} -quiet] -quiet
